select PRSDATENVAR.ORGABTEILUNG, PRSDATENVAR.ORGSTRUCTID from PRSDATENVAR;

select PRSDATENVAR.PRSVORGES_NAME from PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBZEITMODELL from  PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBVH_URLAUB_FLAG, PRSDATENVAR.ARBVH_URLAUB_JAHR from  PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.TARIF_ZULAGE_01, PRSDATENVAR.TARIF_ZULAGE_01, 
PRSDATENVAR.TRF_LSTZUL_FLAG, PRSDATENVAR.TRF_LSTZUL_BETRAG, PRSDATENVAR.TRF_LSTZUL_PROZ, PRSDATENVAR.TRF_LSTZUL_PUNKTE, PRSDATENVAR.TRF_LSTZUL_PUNKTWERT 
from PRSDATENVAR;