select RDB$RELATION_NAME from rdb$relations where RDB$RELATION_NAME like '%LHN%' order by RDB$RELATION_NAME;

/* Einfache Spaltensuche */
select f.rdb$relation_name, f.rdb$field_name from rdb$relation_fields f join rdb$relations r on f.rdb$relation_name = r.rdb$relation_name and r.rdb$view_blr is null 
and (r.rdb$system_flag is null or r.rdb$system_flag = 0) where f.rdb$relation_name like 'PRSDAT%' and f.rdb$field_name like 'BEHIND%' order by 1, f.rdb$field_position;

/* Einfache Spaltensuche */
select f.rdb$field_name from rdb$relation_fields f join rdb$relations r on f.rdb$relation_name = r.rdb$relation_name and r.rdb$view_blr is null 
and (r.rdb$system_flag is null or r.rdb$system_flag = 0) where f.rdb$relation_name like 'PRSDAT%' and f.rdb$field_name like 'BEHIND%' order by 1, f.rdb$field_position;


/* Mehrere Kombis */
select f.rdb$field_name from rdb$relation_fields f join rdb$relations r on f.rdb$relation_name = r.rdb$relation_name and r.rdb$view_blr is null 
and (r.rdb$system_flag is null or r.rdb$system_flag = 0) where f.rdb$relation_name like 'PRSDAT%' 
and (f.rdb$field_name like '%TRF%' OR f.rdb$field_name like 'TARIF%') 
and not (f.rdb$field_name like '%UV%')
order by 1, f.rdb$field_position;




select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBVHID, PRSDATENVAR.SV_NATIONALITAET from PRSDATENVAR;

select PRSDATEN.PRSNUM, PRSDATEN.ANSCHRIFT_BUNDESLAND from PRSDATEN;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBVHID, PRSDATENVAR.ARBVH_STATUS from PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBVHID, PRSDATENVAR.ARBZEITMODELL from PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBVHID, PRSDATENVAR.ARBVH_URLAUB_FLAG, PRSDATENVAR.ARBVH_URLAUB_JAHR from PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.ARBVHID, PRSDATENVAR.UV_PFLICHT from PRSDATENVAR;

select prsnum, TARIF_AT_GEHALT,TARIF_AT_ZUSATZ,TARIF_BETRAG,TARIF_BETRAG_FLAG,TARIF_BETRAG_ZUSATZ,TARIF_ENTGELTMETH,TARIF_GRPZULAGE_BETRAG,
TARIF_GRPZULAGE_FLAG,TARIF_GRPZULAGE_PROZENT,TARIF_GRPZULAGE_STUFDATUM,TARIF_GRPZULAGE_TRFGRUPPE,TARIF_GRPZULAGE_TRFSTUFE,TARIF_GRUPPE,TARIF_PENSION,
TARIF_PENSION_ZUSATZ,TARIF_SONSTENTG,TARIF_SONSTENTG_ZUSATZ,TARIF_STUFE,TARIF_STUFUNG_DATUM,TARIF_STUFUNG_VORGEZ,TARIF_TYP,TARIF_ZULAGE_01,
TARIF_ZULAGE_01_FLAG,TARIF_ZULAGE_02,TARIF_ZULAGE_02_FLAG,TARIF_ZULAGE_03,TARIF_ZULAGE_03_FLAG,TARIF_ZULAGE_04,TARIF_ZULAGE_04_FLAG,
TARIF_ZULAGE_05,TARIF_ZULAGE_05_FLAG,TARIF_ZULAGE_06,TARIF_ZULAGE_06_FLAG,TARIF_ZULAGE_07,TARIF_ZULAGE_07_FLAG,TARIF_ZULAGE_08,TARIF_ZULAGE_08_FLAG,
TARIF_ZULAGE_09,TARIF_ZULAGE_09_FLAG,TARIF_ZULAGE_10,TARIF_ZULAGE_10_FLAG,TARIF_ZULAGE_11,TARIF_ZULAGE_11_FLAG,TARIF_ZULAGE_12,TARIF_ZULAGE_12_FLAG,
TARIF_ZULAGE_13,TARIF_ZULAGE_13_FLAG,TARIF_ZULAGE_14,TARIF_ZULAGE_14_FLAG,TARIF_ZULAGE_15,TARIF_ZULAGE_15_FLAG,TARIF_ZULAGE_16,TARIF_ZULAGE_16_FLAG,
TARIF_ZULAGE_17,TARIF_ZULAGE_17_FLAG,TARIF_ZULAGE_18,TARIF_ZULAGE_18_FLAG,TARIF_ZULAGE_19,TARIF_ZULAGE_19_FLAG,TARIF_ZULAGE_20,TARIF_ZULAGE_20_FLAG,
TARIF_ZULAGE_21,TARIF_ZULAGE_21_FLAG,TARIF_ZULAGE_22,TARIF_ZULAGE_22_FLAG,TARIF_ZULAGE_23,TARIF_ZULAGE_23_FLAG,TARIF_ZULAGE_24,TARIF_ZULAGE_24_FLAG,
TARIF_ZULAGE_25,TARIF_ZULAGE_25_FLAG,TARIF_ZULAGE_26,TARIF_ZULAGE_26_FLAG,TARIF_ZULAGE_27,TARIF_ZULAGE_27_FLAG,TARIF_ZULAGE_28,TARIF_ZULAGE_28_FLAG,
TARIF_ZULAGE_29,TARIF_ZULAGE_29_FLAG,TARIF_ZULAGE_30,TARIF_ZULAGE_30_FLAG,TRF_LSTZUL_ABSBETRG,TRF_LSTZUL_BETRAG,TRF_LSTZUL_FLAG,TRF_LSTZUL_PROZ,
TRF_LSTZUL_PUNKTE,TRF_LSTZUL_PUNKTWERT from PRSDATENVAR;


select prsnum, LST_AGS,LST_ALLGLSTTAB,LST_AUSLANDBESCHFTG,LST_BESLSTTAB_2_FLAG,LST_FAKTOR,LST_FAKTORFLAG,LST_FINANZAMT,LST_FREIBETRG_JAHR,
LST_FREIBETRG_MONAT,LST_FREIBETRG_TAG,LST_FREIBETRG_WOCHE,LST_HINZUBETRG_JAHR,LST_HINZUBETRG_MONAT,LST_HINZUBETRG_TAG,LST_HINZUBETRG_WOCHE,
LST_KINDERFREIBETRG,LST_KONF_ARBNEH,LST_KONF_EHEGAT,LST_PAUSCHALKIST,LST_STEUERKLASSE,LST_STEUERPFLICHTIG,LST_VERSFREIBETRG
from PRSDATENVAR;


select prsnum, LST_ELSTAM_GEBURT_DATUM,LST_JAHRESAUSGLEICH,LST_KEIN_KONFAUSWEIS,LST_STEUERIDNUM,LST_VERSBEZBEGINN,LST_VERSBEZ_01_2005 from PRSDATEN;

select prsnum, BEHIND_ARBZEIT,BEHIND_AUSW_GUELTIGBIS,BEHIND_AUSW_GUELTIGVON,BEHIND_AUSW_NUM,BEHIND_DIENSTST_AZ,
BEHIND_DIENSTST_BEZ,BEHIND_DIENSTST_ORT,BEHIND_DIENSTST_PLZ,BEHIND_DIENSTST_STR,BEHIND_DIENSTST_TYP,BEHIND_FLAG,
BEHIND_PROZENT,BEHIND_PRSGRP,BEHIND_URLAUB_JAHR from PRSDATENVAR;