/* Skript */
update LST_ELSTAM_OUT 
set LST_ELSTAM_OUT.TRANSFERTICKET = NULL, 
LST_ELSTAM_OUT.NUTZDATENTICKET = NULL, 
LST_ELSTAM_OUT.TRANSFERDATE = NULL, 
LST_ELSTAM_OUT.EINGANGSDATUM = NULL,
LST_ELSTAM_OUT.HINWEISCODE = NULL, 
LST_ELSTAM_OUT.HINWEISDATUM = NULL, 
LST_ELSTAM_OUT.HINWEISMESSAGE = NULL, 
LST_ELSTAM_OUT.HINWEISSTEUERNUM = NULL, 
LST_ELSTAM_OUT.HINWEISTYPE = NULL,
LST_ELSTAM_OUT.FREIGABEDATE = '26.07.2106 00:00:00',
LST_ELSTAM_OUT.REFDATUM_AG = '04.01.2016 00:00:00',
LST_ELSTAM_OUT.STATUS = 2
where LST_ELSTAM_OUT.PRSNUM in (78)
and LST_ELSTAM_OUT.DATENART = 3;

Select * from LST_ELSTAM_OUT where LST_ELSTAM_OUT.PRSNUM in (78)
and LST_ELSTAM_OUT.DATENART = 3;
