Select LST_ELSTAM_OUT.PRSNUM, LST_ELSTAM_OUT.STATUS, LST_ELSTAM_OUT.DATENART, LST_ELSTAM_OUT.FINISHDATE, LST_ELSTAM_OUT.NAME_NACHNAME, 
LST_ELSTAM_OUT.NAME_VORNAME, LST_ELSTAM_OUT.STEUERIDNUM,LST_ELSTAM_OUT.STEUERNUM_AG, LST_ELSTAM_OUT.BESCHBEGINN, LST_ELSTAM_OUT.BESCHENDE, LST_ELSTAM_OUT.TRANSFERTICKET
from LST_ELSTAM_OUT where LST_ELSTAM_OUT.PRSNUM in (608) and LST_ELSTAM_OUT.DATENART in (1,3);
