/* 
    SQL Manager Lite for InterBase and Firebird
    SQL Editor queries
 */

/*  Page 1  */

select a.ID, a.PRSNUM, a.STORNOID, a.JAHR, a.KORREKTURJAHR, a.MONAT, a.KORREKTURMONAT, a.KORREKTURSTATUS from KR_BAS as a 
where (a.PRSNUM = 1001 or a.PRSNUM = 1002) 
and a.JAHR = 2016 order by a.PRSNUM, a.MONAT;

SELECT KR_BETRAG.PRSNUM, KR_BETRAG.PARENTID,KR_BAS.STORNOID, KR_BETRAG.KSTART, KR_BETRAG.BETRAG,KR_BAS.KORREKTURJAHR, KR_BAS.KORREKTURMONAT, KR_BETRAG.JAHR, KR_BETRAG.MONAT from KR_BAS LEFT JOIN KR_BETRAG on KR_BAS.ID = KR_BETRAG.PARENTID 
WHERE (KR_BAS.PRSNUM = 1002)
And KR_BAS.JAHR= 2016
AND KR_BETRAG.KSTART not like '[%';



