select PRSDATENVAR.PRSNUM, PRSDATENVAR.KV_SCHL,PRSDATENVAR.KV_BEITRAG, PRSDATENVAR.KV_PRIVBEITRAG_P10_ESTG, PRSDATENVAR.KV_ZUSCHUSS_AG from PRSDATENVAR
where PRSDATENVAR.KV_SCHL = 9;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.KV_SCHL,PRSDATENVAR.KV_BEITRAG, PRSDATENVAR.KV_PRIVBEITRAG_P10_ESTG, PRSDATENVAR.KV_ZUSCHUSS_AG,
PRSDATENVAR.PV_SCHL,PRSDATENVAR.PV_BEITRAG,PRSDATENVAR.PV_PRIVBEITRAG_P10_ESTG, PRSDATENVAR.PV_ZUSCHUSS_AG from PRSDATENVAR