select DISTINCT(PRSDAtENVAr.TARIF_ENTGELTMETH)from PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.TARIF_GRPZULAGE_FLAG, PRSDATENVAR.TARIF_GRPZULAGE_BETRAG, PRSDATENVAR.TARIF_GRPZULAGE_TRFGRUPPE  from PRSDATENVAR where PRSDATENVAR.JAHR = 2016 and PRSDATENVAR.MONAT = 6;;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.LST_FAKTOR, PRSDATENVAR.LST_FAKTORFLAG from PRSDATENVAR where PRSDATENVAR.JAHR = 2016 and PRSDATENVAR.MONAT = 6 and  PRSDATENVAR.LST_FAKTOR is not null;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.LST_FINANZAMT from PRSDATENVAR;
 
select PRSDATENVAR.PRSNUM, PRSDATENVAR.LST from PRSDATENVAR;

select PRSDATENVAR.PRSNUM, PRSDATENVAR.KV_SCHL || PRSDATENVAR.RV_SCHL || PRSDATENVAR.AV_SCHL || PRSDATENVAR.PV_SCHL as Beitragsgruppenschl from PRSDATENVAR;

select distinct(PRSDATENVAR.KV_SCHL || PRSDATENVAR.RV_SCHL || PRSDATENVAR.AV_SCHL || PRSDATENVAR.PV_SCHL) as BGSCHL from PRSDATENVAR; 



select PRSDATENVAR.KV_SCHL || PRSDATENVAR.RV_SCHL || PRSDATENVAR.AV_SCHL || PRSDATENVAR.PV_SCHL as BGS, 
count(PRSDATENVAR.KV_SCHL || PRSDATENVAR.RV_SCHL || PRSDATENVAR.AV_SCHL || PRSDATENVAR.PV_SCHL)
from PRSDATENVAR 
where PRSDATENVAR.JAHR = 2016 and PRSDATENVAR.MONAT = 6  
group by PRSDATENVAR.KV_SCHL || PRSDATENVAR.RV_SCHL || PRSDATENVAR.AV_SCHL || PRSDATENVAR.PV_SCHL;
